### ISSUE TITLE
초보자인데 dll 파일을 어디서 받나요?

### ISSUE THREAD

**Issue by JBlack99** [leejeonghun/san2kr#2]
초보자인데 dll 파일을 어디서 받나요?

**Comment by leejeonghun** [comment]
https://github.com/leejeonghun/san2kr/releases 여기로 가면 다운로드 받으실 수 있습니다.
바로 다운로드 받으시려면 아래 링크를 클릭하셔도 됩니다.
https://github.com/leejeonghun/san2kr/releases/download/v0.5.2/san2kr-v0.5.2.zip

**Comment by JBlack99** [comment]
너무너무 고맙습니다. 본문에도 해당 내용이 있다면 저 같은 github 초보자에게 큰 도움이 될 것 같아요.

**Comment by leejeonghun** [comment]
도움이 되었다니 다행입니다. 여유가 생기면 말씀주신 내용 반영해 보도록 하겠습니다.
